server:
  port: 8088
  servlet:
    context-path: /ditto
jasypt:
  encryptor:
    password: ditto
spring:
  application:
    name: ditto
  datasource:
    url: jdbc:mysql://47.96.9.221:3306/ditto?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 'ENC(qLFCGrfhex35S4hoFAlIrbi1pFea2nHP)'
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 47.96.9.221
    port: 6379
    database: 1
    password: 'ENC(qLFCGrfhex35S4hoFAlIrbi1pFea2nHP)'
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: io.jovi.ditto.entity
